services:
  urlshortener-backend:
    image: haina2410/urlshortener-backend:latest
    ports:
      - '4002:4002'
    env_file:
      - stack.env

  metabase:
    image: metabase/metabase:latest
    ports:
      - '4003:3000'
    env_file:
      - stack.env